name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./Cli/Cli.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore ./Cli/Cli.csproj

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg ./Cli/Cli.csproj

    - name: Publish to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"
